logging:
  level:
    org.palms: debug
    org.springframework.web: trace
    org.apache: trace

server:
  port: 8080
  servlet:
    context-path: /api
spring:
  http:
    encoding:
      enabled: false
  servlet:
    multipart:
      max-request-size: -1
      max-file-size: -1
  application:
    name: mood-tracker-api
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/mood_tracker_db
    username: postgres
    password: postgres404
    driver-class-name: org.postgresql.Driver

open-weather-client:
  url: "https://api.openweathermap.org/data/2.5/"
  api-key: "7fb9de833c483c478a4eecbee32569b7"
  connection-timeout: 3000
  read-timeout: 3000

jwt:
  secretKey: "verysecretkey"
  validityTime: 3600000